In [1]:
!pip install openpyxl

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import folium
#pip install openpyxl --upgrade
pd.set_option('display.max_columns', None)

## Import data

In [3]:
stn_names = pd.read_excel('Data/station-names.xls')
# Downtown SF stations: Embardacadero, Montgomery, Powell St, Civic Center
jan2019 = pd.read_excel('Data/ridership_2019/Ridership_201901.xlsx', header=1, index_col=0)
jan2022 = pd.read_excel('Data/ridership_2022/Ridership_202201.xlsx', header=1, index_col=0)
jan2022.head()

RM          EN          EP         NB          BK         AS  \
RM    9.333333   50.190476   41.619048  27.000000  140.904762  37.619048   
EN   57.666667   12.809524   40.904762  30.857143  227.333333  41.047619   
EP   45.428571   34.095238    6.761905  22.523810  170.333333  23.714286   
NB   28.619048   26.285714   24.000000   5.476190   64.714286  16.714286   
BK  153.285714  238.190476  183.428571  68.428571   19.523810  86.047619   

           MA          19          12         LM         FV         CL  \
RM  56.047619   40.571429   44.000000  11.904762  40.571429  25.047619   
EN  81.714286   82.619048  112.238095  25.047619  47.523810  34.095238   
EP  42.857143   44.761905   56.476190  14.952381  24.761905  10.238095   
NB  27.428571   35.571429   33.333333  10.619048  32.571429  11.714286   
BK  96.238095  105.095238  110.809524  41.190476  93.285714  45.380952   

           SL         BF         HY         SH         UC         FM  \
RM  16.142857   7.809524  13.952381   7.095238   6.190476   5.904762   
EN  20.000000  16.047619  19.952381   9.714286  13.666667  12.857143   
EP  14.619048   6.904762   7.095238   5.190476   4.714286   6.142857   
NB  10.857143   7.333333   5.714286   2.333333   4.428571   5.380952   
BK  49.952381  29.523810  28.857143  17.619048  25.285714  21.904762   

           CN         PH         WC         LF         OR         RR  \
RM   9.619048   3.142857  10.380952   4.666667   3.380952   8.952381   
EN  10.809524   5.047619  13.142857   3.285714   5.380952  11.761905   
EP   6.428571   2.238095   5.952381   3.142857   2.380952  12.095238   
NB   5.047619   5.857143   5.238095   1.809524   3.476190   4.190476   
BK  22.571429  21.952381  24.380952  12.809524  10.095238   9.714286   

           OW          EM          MT          PL          CC         16  \
RM  14.047619  128.047619   97.523810  173.761905  102.285714  91.428571   
EN  19.190476  253.761905  196.571429  287.476190  218.047619  96.000000   
EP   4.238095   95.571429   94.714286   89.476190   86.428571  31.285714   
NB   5.142857   69.761905   72.714286   72.333333   80.904762  33.523810   
BK  28.380952  139.666667  106.000000  153.333333  130.523810  70.142857   

           24         GP         BP         DC         CM        CV  \
RM  87.476190  20.523810  26.285714  17.666667   9.571429  2.619048   
EN  84.857143  26.857143  31.619048  24.761905  10.190476  2.761905   
EP  29.523810  10.000000   8.000000   6.619048   1.000000  1.619048   
NB  22.809524   7.047619  12.333333   6.380952   2.952381  3.380952   
BK  63.761905  26.952381  22.380952  17.571429   4.142857  8.904762   

           ED        NC         WP        SS         SB         SO         MB  \
RM   5.238095  1.619048   5.285714  4.857143   9.190476  15.523810   7.809524   
EN   7.904762  3.952381   5.285714  7.380952  12.571429  43.666667  19.285714   
EP   3.238095  1.095238   4.142857  3.904762   2.142857  19.714286   4.952381   
NB   3.714286  1.095238   3.619048  2.571429   1.761905  27.285714   3.523810   
BK  17.238095  6.857143  15.761905  5.428571   7.904762  73.190476  22.714286   

          WD         OA         WS         ML         BE        PC         AN  \
RM  2.047619   4.476190   7.000000   3.190476   4.142857  5.095238   6.523810   
EN  2.000000  13.714286   9.809524   5.333333   6.476190  3.095238   4.619048   
EP  2.285714   5.809524   4.761905   2.714286   5.142857  1.761905   2.476190   
NB  1.333333   8.095238   3.523810   1.857143   3.142857  0.714286   2.523810   
BK  5.428571  35.285714  13.380952  14.238095  22.047619  5.190476  14.904762   

          Exits  
RM  1475.285714  
EN  2332.714286  
EP  1096.428571  
NB   832.761905  
BK  2546.904762

#### Calculate sum of entry ridership at each downtown SF station

In [4]:
# 2019
dwntwnSF_jan2019 = jan2019[['EM', 'MT', 'PL', 'CC']]
sums_SF_jan2019 = np.array(np.sum(dwntwnSF_jan2019))  # rider entry sums across all stations
sums_SF_jan2019

array([81936.57142857, 86109.61904762, 56924.95238095, 46029.04761905])

In [5]:
# 2022
dwntwnSF_jan2022 = jan2022[['EM', 'MT', 'PL', 'CC']]
sums_SF_jan2022 = np.array(np.sum(dwntwnSF_jan2022))
sums_SF_jan2022

array([11328.        , 10255.42857143, 14372.95238095, 10294.76190476])

#### Calculate sum of entry ridership at each Berkeley station

In [6]:
# 2019
berk_jan2019 = jan2019[['BK', 'NB']]
sums_berk_jan2019 = np.array(np.sum(berk_jan2019))  # rider entry sums across all stations
sums_berk_jan2019

array([18904.19047619,  8182.95238095])

In [7]:
# 2022
berk_jan2022 = jan2022[['BK', 'NB']]
sums_berk_jan2022 = np.array(np.sum(berk_jan2022))
sums_berk_jan2022

array([4803.04761905, 1652.47619048])

## Mapping

### San Francisco

#### Calculate total percent difference between 2019 and 2022 for each station

In [9]:
SF_percent_diffs = (sums_SF_jan2022 - sums_SF_jan2019) / sums_SF_jan2019

#### Plot percent differences on map

In [10]:
# @source: https://www.python-graph-gallery.com/313-bubble-map-with-folium

# Make an empty map
SF_map = folium.Map(location=[37.78656375,-122.4051605], tiles="cartodbpositron", zoom_start=15)

In [11]:
# Make a data frame with dots to show on the map
SF_mapping_df = pd.DataFrame({
   'lon':[-122.3970, -122.401942, -122.4080, -122.4137],
   'lat':[37.7929, 37.789355, 37.7844, 37.7796],
   'name':['Embarcadero: '+str(round(SF_percent_diffs[0]*100))+'%', 
           'Montgomery Street: '+str(round(SF_percent_diffs[1]*100))+'%', 
           'Powell Street: '+str(round(SF_percent_diffs[2]*100))+'%', 
           'Civic Center: '+str(round(SF_percent_diffs[3]*100))+'%'],
   'value': SF_percent_diffs
}, dtype=str)

SF_mapping_df

lon        lat                     name                value
0     -122.397    37.7929        Embarcadero: -86%  -0.8617467169727105
1  -122.401942  37.789355  Montgomery Street: -88%  -0.8809026368383158
2     -122.408    37.7844      Powell Street: -75%  -0.7475105067323393
3    -122.4137    37.7796       Civic Center: -78%  -0.7763420614311872

In [12]:
# add marker one by one on the map
colors = np.array(['crimson', 'orange', 'green', 'blue'])

for i in range(len(SF_mapping_df)):
    folium.Circle(
      location=[SF_mapping_df.iloc[i]['lat'], SF_mapping_df.iloc[i]['lon']],
      tooltip=SF_mapping_df.iloc[i]['name'],
      radius=float(SF_mapping_df.iloc[i]['value'])*-380,
      color=colors[0],
      fill=True,
      fill_color=colors[0]
   ).add_to(SF_map)

# Show the map again
SF_map

In [13]:
SF_map.save('figures/SF_interactive_map.html')

### Berkeley

In [14]:
berk_percent_diffs = (sums_berk_jan2022 - sums_berk_jan2019) / sums_berk_jan2019

In [15]:
# Make an empty map
berk_map = folium.Map(location=[37.8715, -122.2730], tiles="cartodbpositron", zoom_start=15)

In [16]:
# Make a data frame with dots to show on the map
berk_mapping_df = pd.DataFrame({
   'lon':[-122.2681, -122.2834],
   'lat':[37.8701, 37.8740],
   'name':['Downtown Berkeley: '+str(round(berk_percent_diffs[0]*100))+'%', 
           'North Berkeley: '+str(round(berk_percent_diffs[1]*100))+'%'],
   'value': berk_percent_diffs}, dtype=str)

berk_mapping_df

lon      lat                     name                value
0  -122.2681  37.8701  Downtown Berkeley: -75%  -0.7459268290225398
1  -122.2834   37.874     North Berkeley: -80%  -0.7980586818123625

In [17]:
# add marker one by one on the map
colors = np.array(['crimson', 'orange', 'green', 'blue'])

for i in range(len(berk_mapping_df)):
    folium.Circle(
      location=[berk_mapping_df.iloc[i]['lat'], berk_mapping_df.iloc[i]['lon']],
      tooltip=berk_mapping_df.iloc[i]['name'],
      radius=float(berk_mapping_df.iloc[i]['value'])*-400,
      color=colors[0],
      fill=True,
      fill_color=colors[0]
   ).add_to(berk_map)

# Show the map again
berk_map

In [18]:
berk_map.save('figures/berkeley_interactive_map.html')